#!/bin/bash

name='ensembl-tools'
url="https://github.com/Ensembl/ensembl-tools/archive/release/96.zip"

get_src "$name" "$url"
uncompress_pkg "$name"
mv $RBBT_SOFTWARE_DIR/.build/ensembl-tools-release-*/ $RBBT_SOFTWARE_DIR/opt/$name
