#!/bin/bash

name='ensembl-tools'
url="https://github.com/Ensembl/ensembl-tools/archive/release/81.zip"

get_src "$name" "$url"
uncompress_pkg "$name"
mv $RBBT_SOFTWARE_DIR/.build/ensembl-tools-release-81/ $RBBT_SOFTWARE_DIR/opt/$name
cd  $RBBT_SOFTWARE_DIR/opt/$name/scripts/variant_effect_predictor && 
  perl INSTALL.pl -a ac -s homo_sapiens -y GRCh37 -c $RBBT_SOFTWARE_DIR/opt/$name/Data.GRCh37


